
FROM openjdk:latest

LABEL maintainer="javaguides.net"
ADD ./build/libs/ServiceDiscoveryOnlineTrainingPortal-0.0.1-SNAPSHOT.jar servicediscovery.jar

ENTRYPOINT ["java", "-jar", "servicediscovery.jar"]